#' uniHM Sample Data
#'
#' Sample data for illustrating a new heatmap design that can display both the differential pattern and 
#' referenced quality of signature genes/down-regulated signature genes.
#'
#' @format ## `sample_data_uniHM`
#' A data frame with 12 rows and 10 columns:
"sample_data_uniHM"

#' MGpI Sample Data
#'
#' Sample data extracted from GSE19380 using only 16 pure samples from 4 groups (Primary neuronal culture,
#' Primary astrocytic culture, Primary oligodendrocytic culture, Primary microglial culture) according to the phenotypic data.
#' Then missing values are manually introduced by two mechanisms: lower limit of detection (LLOD) and missing at random (MAR),
#' with totally ~80,000 missing values and ~16,000 (20%) missing due to MAR. Features with all values missing are removed.
#'
#' @format ## `sample_data_MGpI`
#' A data frame with 29,772 rows and 16 columns:
"sample_data_MGpI"

#' eCOT Sample Data
#'
#' Sample data generated by Dirichlet distribution, with added signature genes (SGs) and down-regulated signature genes (DSGs).
#'
#' @format ## `sample_data_eCOT`
#' A data frame with 2753 rows and 3 columns:
"sample_data_eCOT"